# Generated by Django 4.2.6 on 2024-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.DateField(null=True)),
                ('intensity', models.IntegerField(blank=True)),
                ('sector', models.CharField(max_length=250)),
                ('topic', models.CharField(max_length=100)),
                ('insight', models.CharField(max_length=250, null=True)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('start_year', models.DateField(null=True)),
                ('impact', models.CharField(blank=True, max_length=150, null=True)),
                ('added', models.DateTimeField(null=True)),
                ('published', models.DateField(null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
