# Generated by Django 4.2.6 on 2024-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_dashboard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
